### ISSUE TITLE
.RecordFullCrudServiceImplTest > create java.lang.NullPointerException

### ISSUE THREAD

**Issue by vskurikhin** [vskurikhin/daybook#74]
[Test worker] ERROR su.svn.showcase.services.impl.NewsEntryFullCrudServiceImpl - Error with DBEntity : class su.svn.showcase.domain.NewsEntry and id : 00000000-0000-0000-0000-000000000001
    [Test worker] ERROR su.svn.showcase.services.impl.NewsEntryFullCrudServiceImpl - Can't consume because had the exception 
    java.lang.NullPointerException
        at su.svn.showcase.services.impl.NewsEntryFullCrudServiceImpl.lambda$storageConsumer$0(NewsEntryFullCrudServiceImpl.java:109)
        at su.svn.showcase.services.impl.AbstractUserTransactionService.consume(AbstractUserTransactionService.java:85)
        at su.svn.showcase.services.impl.NewsEntryFullCrudServiceImpl.create(NewsEntryFullCrudServiceImpl.java:57)

**Comment by vskurikhin** [comment]
fixed
